import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    excel: 'src/excel/index.ts',
    csv: 'src/csv/index.ts',
    pdf: 'src/pdf/index.ts',
    web: 'src/web/index.ts',
    mime: 'src/mime/index.ts',
    logger: 'src/logger/index.ts',
    rjsf: 'src/rjsf/index.ts',
  },
  format: ['esm', 'cjs'],
  dts: true,
  splitting: false,
  clean: true,
  treeshake: true,
  sourcemap: true,
  target: 'es2022',
  outDir: 'dist',
  external: [
    'exceljs',
    'papaparse',
    'jspdf',
    'jspdf-autotable',
    'mime',
    'pino',
    'i18next',
    'react-i18next',
    '@rjsf/utils',
    'ajv-i18n',
    '@rjsf/validator-ajv8',
  ],
});
