#!/usr/bin/env sh

# exit immediately if any command fails
set -e

echo "Running knip to detect unused dependencies or dead code..."
bun run knip
echo "✅ Knip completed"

echo "Running tests..."
bun run test
echo "✅ Tests completed"
